### ISSUE TITLE
LDAPでActiveDirectoryの設定をしたが、ログインテストでエラーとなる

### ISSUE THREAD

**Issue by hosokawatakeshi** [weseek/growi#2695]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS7.7|
|GROWI     |4.0.2-RC|
|node.js   |12.17.0|
|npm       |6.14.4|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10|
|browser   |Chrome 84.0.4147.135|

How to reproduce? (再現手順)
---------------------------

1. セキュリティ設定で認証機構設定でLDAPを選択する。
1. LDAP を有効にするを有効にする。
1. Server URLに以下を入力する。
    ```
   ldaps://hostname.domain.local:636/dc=domain,dc=local 
    ```
1. Bind モードを管理者Bindに設定する。
1. Bind DNをadmin@domain.localに設定する。
1. Bind DN パスワードにパスワードを設定する。
1. 検索フィルターに以下を設定する。
   ```
   (sAMAccountName={{ username }})
   ```
1. Attribute Mapping (オプション)のユーザー名に以下を設定する。
   ```
   sAMAccountName
   ```
1. Attribute Mapping (オプション)の新規ログイン時、username が一致したローカルアカウントが存在した場合は自動的に紐付けるにチェックを入れる。
1. Attribute Mapping (オプション)のメールアドレスに以下を設定する。
   ```
   mail
   ```
1. Attribute Mapping (オプション)の名前に以下を設定する。
   ```
   sN
   ```
1. 更新ボタンを押す。
1. ログインテストを押す。
1. ユーザ名・パスワードを入れて、Testボタンを押す。
1. LDAP Server Error occured.というメッセージが表示され、Logsに以下が表示される。
   ```
   Wed Aug 26 2020 10:39:10 GMT+0900 (日本標準時) - LDAP Server Error occured.

   Wed Aug 26 2020 10:39:10 GMT+0900 (日本標準時) - [object Object]
   ```

What happens? (症状)
---------------------

- LDAP Server Error occured.が表示される。

What is the expected result? (期待される動作)
-------------------------------------------

- LDAPのログインに成功する。

Note
----

- object Objectというエラーの意味が分かりません。
- GitLabやOpenProjectでLDAPSの設定は確認しており、接続可能となっています。
- GitLabは、Encryptionをsimple_tlsで設定しておりますが、Growiは設定項目がないのでしょうか。

**Comment by yuki-takei** [comment]
@hosokawatakeshi 

> object Objectというエラーの意味が分かりません。

こちらはLDAP接続でのロギングに関するバグですね…別途調べてみます。

今回のケースに関しては、画面上ではなく GROWI サーバー側の stdout にログが出ていると思うのですが、そちらは確認できないでしょうか？

**Comment by hosokawatakeshi** [comment]
errorの内容は以下の通りです。
```
app_1            | [2020-08-28T04:47:05.498Z] ERROR: growi:routes:login-passport/75 on 1fcbbd57211c:
app_1            |   LDAP Server Error:  Error: unable to verify the first certificate
app_1            |       at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
app_1            |       at TLSSocket.emit (events.js:314:20)
app_1            |       at TLSSocket._finishInit (_tls_wrap.js:932:8)
app_1            |       at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
app_1            |     code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
app_1            |   }
```

**Comment by yuki-takei** [comment]
@hosokawatakeshi 反応が遅くて申し訳ないです。

TLS関連のエラーが出ているので、自己署名証明書絡みか、もしくはネットワーク的に中間証明書に辿り着けないという問題があるのかもしれません。

症状としてはこちらの記事が近いように思います。

https://www.zu-min.com/archives/505

## GROWI 側の設定について

[passport-ldapauth](https://www.npmjs.com/package/passport-ldapauth) というパッケージを利用しているのですが、WESEEK, Inc. での利用では LDAPS で接続ができています。ただこのパッケージで設定可能な `tlsOption` を細かく設定できる機能は今のところ GROWI では実装されていないので、その辺りの設定次第、という可能性はあります。

参考までに、GitLab でどのような設定を利用されているのか、記述できる範囲で書いていただくことは可能でしょうか？

**Comment by hosokawatakeshi** [comment]
GitLabは、gitlab.rbに以下を設定しています。
```
gitlab_rails['ldap_enabled'] = true
gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
   main: # 'main' is the GitLab 'provider ID' of this LDAP server
     label: 'LDAP'
     host: 'ActiveDirectoryサーバ'
     port: 636
     uid: 'sAMAccountName'
     bind_dn: 'ユーザ名@ドメイン'
     password: 'パスワード'
     encryption: 'simple_tls' # "start_tls" or "simple_tls" or "plain"
     verify_certificates: false
     smartcard_auth: false
     active_directory: true
     allow_username_or_email_login: false
     lowercase_usernames: false
     block_auto_created_users: false
     base: 'DC=ドメイン,DC=local'
     user_filter: ''
     attributes:
      username: ['sAMAccountName']
      email:    ['mail', 'userPrincipalName']
      name:       'cn'
      first_name: 'givenName'
      last_name:  'sn'
EOS
```
あとは、Jenkinsにも設定しましたが、大丈夫でした。
