### ISSUE TITLE
Bug: no-cdn環境でdraw.io(diagrams.net)で描画した図のSVGファイルが外部参照になる / SVG files of diagrams drawn by draw.io (diagrams.net) in no-cdn environment depend on the Internet connection.

### ISSUE THREAD

**Issue by tunegin** [weseek/growi#3546]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |CentOS Linux release 7.9.2009 (Core)|
|GROWI     |4.2.13|
|node.js   |14.16.0|
|npm       |6.14.11|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

**Dockerfile**で`weseek/growi:4-nocdn`を指定。

**docker-compose.yml**
```yml
version: '3'

services:
  drawio:
    image: fjudith/draw.io
    container_name: drawio
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      PUBLIC_DNS: domain
      ORGANISATION_UNIT: unit
      ORGANISATION: org
      CITY: city
      STATE: state
      COUNTRY_CODE: country
      DRAWIO_GITLAB_URL: http://mygitlab.net
      DRAWIO_GITLAB_ID: change_to_your_app_id
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
#      - 127.0.0.1:3000:3000    # localhost only by default
      - 80:3000
    links:
      - mongo:mongo
      - elasticsearch:elasticsearch
    depends_on:
      - mongo
      - elasticsearch
      - drawio
    environment:
      - NO_CDN=true
      - PLANTUML_URI=http://172.17.129.70:8081/plantuml/
      - DRAWIO_URI=http://172.17.129.70:8080/?offline=1&https=0
      - MONGO_URI=mongodb://mongo:27017/growi
      - ELASTICSEARCH_URI=http://elasticsearch:9200/growi
      - PASSWORD_SEED=changeme
      # - FILE_UPLOAD=mongodb   # activate this line if you use MongoDB GridFS rather than AWS
      - FILE_UPLOAD=local     # activate this line if you use local storage of server rather than AWS
      # - MATHJAX=1             # activate this line if you want to use MathJax
      # - PLANTUML_URI=http://  # activate this line and specify if you use your own PlantUML server rather than public plantuml.com
      - HACKMD_URI=http://172.17.129.70:3100    # activate this line and specify HackMD server URI which can be accessed from GROWI client browsers
      - HACKMD_URI_FOR_SERVER=http://hackmd:3000  # activate this line and specify HackMD server URI which can be accessed from this server container
      # - FORCE_WIKI_MODE='public'    # activate this line to force wiki public mode
      # - FORCE_WIKI_MODE='private'   # activate this line to force wiki private mode

    command: "dockerize
              -wait tcp://mongo:27017
              -wait tcp://elasticsearch:9200
              -timeout 60s
              npm run server:prod"
    restart: unless-stopped
    volumes:
      - growi_data:/data

  mongo:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: ./Dockerfile
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"  # increase amount if you have enough memory
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

volumes:
  growi_data:
  mongo_configdb:
  mongo_db:
  es_data:

```

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro 20H2|
|browser   |Microsoft Edge 85.0.564.67|

How to reproduce? (再現手順)
---------------------------

1. ページ内でdraw.ioアイコンを選択し、エディタを起動する。<br>Select the draw.io icon in the page to launch the editor.
1. Active DirectoryのWindows Domainシェイプをキャンバスに配置する。<br>Place the Windows-Domain shape in Active Directory on the canvas.
```
::: drawio
jZPJboMwEEC/hmvEUkJ7zdL2UqlSKvUYuXhiRrIxMk4g/foOMEBQFKkX7HmzeDaCZGvaNyeq4sNK0EEcyjZIdkEcR+skpqMj14FkaToA5VCy0QwO+AsMQ6ZnlFAvDL212mO1hLktS8j9ggnnbLM0O1m9fLUSCu7AIRf6nn6j9AXTaP0yK94BVcFPP8fZoDBiNOZK6kJI29ygZB8kW2etH26m3YLumjf2ZfB7faCdEnNQ+v848CAuQp+5Ns7LX8diRV0NPTxhC+S2qcChAQ+OGEWjpsPnjDaFN5o0EV2FRlXSPadset1UbkiCFHXRBeyFuhI5lurLVgQSAmj6IYznDo2iMjT+0FfkHi9wlOgoM+uuhBosKXJ9lNYILFf1RZEvFwfOQ/uwQdHUdtpXsFRGFzBkhzTlSfGqxhnLzTz40aS4GflTvOKdFrxsaoo9z4MuPJJRnEff625+oGT/Bw==
::: 
```
1. 保存ボタンを押して編集画面に戻る。<br>Click the Save button to return to the editing screen.

What happens? (症状)
---------------------

- プレビュー画面、記事上に意図したシェイプではなく破損した画像ファイルアイコンが表示される。<br>The corrupted image file icon is displayed on the preview screen and on the article.
- https://app.diagrams.net/img/lib/active_directory/windows_domain.svg を読みに行ってしまう。<br>（draw.io上はhttp://172.17.129.70:8080/img/lib/active_directory/windows_domain.svg を読みに行って正しく表示されている。）<br>It tries to download images from the Internet.

What is the expected result? (期待される動作)
-------------------------------------------

- 記事上に意図したシェイプが正しく表示される。<br>The correct shape will appear on the article.
- プレビュー画面、記事上でhttps://app.diagrams.net/ ではなくローカルのサーバに読みに行く。<br>It accesses a local server on the preview screen and on the article, not on the Internet.

Note
----

- 
-
