### ISSUE TITLE
Bug:　IMEの変換候補の表示場所が入力文字列の直下でない

### ISSUE THREAD

**Issue by tnagai-github** [weseek/growi#6878]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |ubuntu|
|GROWI     |5.1.4|
|node.js   |16.17.0|
|npm       |8.15.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |windows|
|browser   |firefox/Edge|

How to reproduce? (再現手順)
---------------------------

ページを編集する

What happens? (症状)
---------------------

- IMEでだされる変換のウィンドウと入力中の文字列の位置関係がおかしい。

- Edge・windows標準のIMEでは半分隠れることが多い
![image](https://user-images.githubusercontent.com/18503156/199402730-b8c53423-833b-4f91-870a-4bbaa3cffc28.png)

-  firefox・ATOKでもかくれることがおおい。また、よく分からない位置に飛ぶこともある。
![image](https://user-images.githubusercontent.com/18503156/199403277-e6c0c8b1-0073-458d-b5ff-893408c08dcf.png)

What is the expected result? (期待される動作)
-------------------------------------------

- IMEのウィンドウは入力文字手列の直下に来る
- たとえば

![image](https://user-images.githubusercontent.com/18503156/199402620-7395e9b9-e413-4f83-aaf9-0d2df1bcc663.png)

Note
----

**Comment by mdameloper3peke** [comment]
if you excuse unfundamental solution, you can add to Custom CSS below code

`
.react-codemirror2 .CodeMirror div {
  bottom: 1.5em;
}
`

**Comment by tthogehoge** [comment]
```css
.react-codemirror2 .CodeMirror div { bottom: 1.5em; }
```

In my environment, this didn't work if I opened the editor many times.

The `textarea` should be displayed under `first-child`, but for some reason it doesn't.
The following is now acceptable. Although the layout will be slightly broken.
I don't know why, but when I do the following, the `textarea` is displayed at the bottom.

```css
.CodeMirror-wrap > div > textarea {
  font-size: inherit !important;
  bottom: -1.5em !important;
}
.CodeMirror-wrap > div:first-child {
  height: 1.5em !important;
}
```

If the text is large, the position will shift, so I made the header size a little smaller.

```css
.cm-header-1 {
  font-size: 1.4em !important;
}
.cm-header-2 {
  font-size: 1.35em !important;
}
.cm-header-3 {
  font-size: 1.3em !important;
}
.cm-header-4 {
  font-size: 1.25em !important;
}
```
