### ISSUE TITLE
カスタムCSSの優先度が低い

### ISSUE THREAD

**Issue by tthogehoge** [weseek/growi#7511]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |debian 11|
|GROWI     |6.0.10|
|node.js   |16.19.1|
|npm       |8.19.3|
|yarn      |1.22.19|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | windows 10|
|browser   |chrome 111.0.5563.66|

How to reproduce? (再現手順)
---------------------------

1. カスタムCSSを設定
    ```css
body {
  font-size: 11px;
}

.wiki ol, .wiki ul {
    margin: 0.1rem 0;
  padding left: 0rem;
}

.wiki ol li, .wiki ul li {
    line-height: 1rem;
  margin: 0px 0;
}
    ```
1. ブラウザで表示

What happens? (症状)
---------------------

- v5ではhtml headerの最後にカスタムCSSが読まれていたがv6では最初の方に読まれる
- カスタムCSSの優先度が低い

What is the expected result? (期待される動作)
-------------------------------------------

- marginが0になること

**Comment by yuki-takei** [comment]
@tthogehoge こちらの症状ですが、バグではなく仕様という扱いにさせていただきます。

## 経緯
- フレームワークを Next.js に変えたことにより、カスタム CSS 注入の場所をコントロールできなくなった
- その影響で、「同一セレクタに対する記述の順序による優先」が不可能になった

## 仕様

v6 以降、以下の仕様とさせていただきます。
「CSS の優先度をその読み込み順に期待するのは不確かであるため、明確に優先されるセレクタを書くべき」

## ワークアラウンド

以上の仕様を踏まえ、ワークアラウンドとしてはセレクタの変更になります。
例えば、`:root` を全てのセレクタの頭につけるなどしてください。

```css
:root body {
  font-size: 11px;
}
```


-----

v5 までの仕様と異なるためご不便をおかけいたしますが、ご理解の程よろしくお願いいたします。
