### ISSUE TITLE
nothing appears on the Attachment Data page after upgraded GROWI from version 4.1 to 6.2.1

### ISSUE THREAD

**Issue by sevenjay** [weseek/growi#8177]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 22.04|
|GROWI     |6.2.1|
|node.js   |18.18.0|
|npm       |9.8.1|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

List of environment variables
FILE_UPLOAD	local
MAX_FILE_SIZE	10485760
ELASTICSEARCH_URI	http://elasticsearch:9200/growi

How to reproduce? (再現手順)
---------------------------
Using the official docker-compose.yml, upgrading GROWI from version 4.1 to 6.2.1.
First upgrade mongodb to 6.0, and mongodb needs to be upgraded one version at a time
```yml=docker-compose.yml
version: '3'

services:
  mongo:
    image: mongo:3.6
    restart: unless-stopped
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db


volumes:
  mongo_configdb:
  mongo_db:
```
Repeat the following until 3.6 4.0 4.2 4.4 5.0 6.0
```
sed -i "s/mongo:3.6/mongo:4.0/g" docker-compose.yml
docker-compose up -d
# this command will update the db to use the new version features
docker exec -it growi-mongo-1 bash -c 'mongo --eval "db.adminCommand( { setFeatureCompatibilityVersion: \"4.0\" } )"'
# should see an output like this
{ "ok" : 1 }
docker-compose down
```
The last 6.0 instructions are
`docker exec -it growi-mongo-1 bash -c 'mongosh --eval "db.adminCommand( { setFeatureCompatibilityVersion: \"6.0\" } )"'`

``` sh
git clone https://github.com/weseek/growi-docker-compose.git growi
cd growi
nano docker-compose.yml
```
``` yml
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:3000    # localhost only by default
    links:
      - mongo:mongo
      - elasticsearch:elasticsearch
    depends_on:
      - mongo
      - elasticsearch
    environment:
      - MONGO_URI=mongodb://mongo:27017/growi
      - ELASTICSEARCH_URI=http://elasticsearch:9200/growi
      - PASSWORD_SEED=changeme
      - FILE_UPLOAD=local     # activate this line if you use local storage of server rather than AWS
      - MAX_FILE_SIZE=10485760
      - TZ=Asia/Taipei

    entrypoint: "dockerize
                  -wait tcp://mongo:27017
                  -wait tcp://elasticsearch:9200
                  -timeout 60s
                  /docker-entrypoint.sh"
    command: ["yarn migrate && node -r dotenv-flow/config --expose_gc dist/server/app.js"]

    restart: unless-stopped
    volumes:
      - growi_data:/data

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db

  elasticsearch:
    build:
      context: ./elasticsearch/v8
      dockerfile: ./Dockerfile
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"  # increase amount if you have enough memory
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true # CVE-2021-44228 mitigation for Elasticsearch <= 6.8.20/7.16.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch/v8/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

volumes:
  growi_data:
  mongo_configdb:
  mongo_db:
  es_data:
```

What happens? (症状)
---------------------

 The issue is that nothing appears on the Attachment Data page.
Even upload a new file.
![image](https://github.com/weseek/growi/assets/1086156/d413344e-f65f-4c28-b9a4-021ceafe4aff)

The path on the host is:
Path is /var/lib/docker/volumes/growi_growi_data/_data/uploads/attachment.

What is the expected result? (期待される動作)
-------------------------------------------

should something on the Attachment Data page
