### ISSUE TITLE
インデックスの状態が「リビルド中 または 破損しています」から変わらない、インデックスが構築されない

### ISSUE THREAD

**Issue by kenichi-fk** [weseek/growi#9196]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 22.04.5 LTS|
|GROWI     |7.0.20|
|node.js   |20.17.0|
|npm       |10.8.2|
|yarn      |1.22.22|
|Using Docker|yes|
|Using [growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 10 Pro|
|browser   |Floorp 11.19.0|

How to reproduce? (再現手順)
---------------------------

1. GROWI に管理者でログイン
1. 管理画面 -> 全文検索管理 -> インデックスのリビルド

What happens? (症状)
---------------------

- 接続の状態: 接続されています
- インデックスの状態: 正規化されています
- この状態でインデックスのリビルドをクリックすると、リビルドの進行状況は0/0のまま、待っていても変わらない。
- ブラウザを更新してみると、インデックスの状態は「リビルド中または破損しています」になり、インデックスのサマリにはgrowi-tmp と growi の2つが表示されています。
- インデックスの正規化 をクリックすると、インデックスの状態は「正規化されています」に戻り、インデックスのサマリも growi だけに戻るが、インデックスは空のままです。
- 何度やってもこの繰り返しとなります。

```
インデックスのサマリ(growi)
{
  "uuid": "BF5vaNVJTNWWnk01FN40Xw",
  "health": "yellow",
  "status": "open",
  "primaries": {
    "docs": {
      "count": 0,
      "deleted": 0
    },
    "store": {
      "size_in_bytes": 225,
      "total_data_set_size_in_bytes": 225,
      "reserved_in_bytes": 0
    },
    "indexing": {
      "index_total": 0,
      "index_time_in_millis": 0,
      "index_current": 0,
      "index_failed": 0,
      "delete_total": 0,
      "delete_time_in_millis": 0,
      "delete_current": 0,
      "noop_update_total": 0,
      "is_throttled": false,
      "throttle_time_in_millis": 0,
      "write_load": 0
    }
  },
  "total": {
    "docs": {
      "count": 0,
      "deleted": 0
    },
    "store": {
      "size_in_bytes": 225,
      "total_data_set_size_in_bytes": 225,
      "reserved_in_bytes": 0
    },
    "indexing": {
      "index_total": 0,
      "index_time_in_millis": 0,
      "index_current": 0,
      "index_failed": 0,
      "delete_total": 0,
      "delete_time_in_millis": 0,
      "delete_current": 0,
      "noop_update_total": 0,
      "is_throttled": false,
      "throttle_time_in_millis": 0,
      "write_load": 0
    }
  }
}
```

What is the expected result? (期待される動作)
-------------------------------------------

- インデックスの再構築が正常にされること。
- 

Note
----

- Elasticsearch の volume が壊れたのかと思い、一旦 volume の es_data を削除して、さらにイメージもすべて削除して docker compose で最新のイメージを構築しましたが、状況は変わりませんでした。

docker-compose.yml の elasticsearch は以下の通りです。
```
  elasticsearch:
    build:
      context: ./elasticsearch/v8
      dockerfile: ./Dockerfile
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"  # increase amount if you have enough memory
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true # CVE-2021-44228 mitigation for Elasticsearch <= 6.8.20/7.16.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch/v8/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
```
- 以前は問題なく検索できていましたが、インデックスのリビルド後からインデックスがなくなってしまい、検索が何もHITしなくなりました。

以上、よろしくお願いいたします。
素晴らしいアプリに感謝しています。
